[package]
name = "adb_helper"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eframe = "0.22.0"
image = "0.24.6"
mdns-sd = "0.7.3"
qrcode-generator = "4.1.8"
rand = "0.8.5"
regex = "1.9.1"
